import Head from "next/head";
import Image from "next/image";
import Navbar from "./components/Navbar";
import styles from "../styles/Home.module.css";
import PortfolioHome from "./components/PortfolioHome";
import { motion } from "framer-motion";
import About from "./about";

export default function Home() {
	return (
		<div className='overflow-hidden'>
			<Head>
				{/*<title>Arian Portfolio</title>*/}
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<Navbar />
			</header>
			<main className={styles.main}>
				<>
					<PortfolioHome
						title="Oh hello there!"
						presentation="I'm Arian Collaso"
					/>
          <motion.div className="flex flex-col justify-start mx-auto w-1/4 mt-10"
					  initial={{opacity: 0, y: 700}}
			   animate={{opacity: 1, y: 0}}
			   transition={{duration: 1.5}}>
          <hr/>
          </motion.div>
				</>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
